# Generated by Django 6.0.1 on 2026-06-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
        ('quizzes', '0004_remove_course_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choices',
            field=models.ManyToManyField(related_name='choices', to='quizzes.choice'),
        ),
    ]
