# Generated by Django 6.0.1 on 2026-03-07 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
