# Generated by Django 6.0.1 on 2026-03-07 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_quizsession_is_active'),
        ('quizzes', '0005_alter_quiz_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='quizsession',
            constraint=models.UniqueConstraint(fields=('user', 'quiz'), name='unique_user_quiz'),
        ),
    ]
