# Generated by Django 6.0.1 on 2026-03-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_quizsession_unique_user_quiz'),
        ('quizzes', '0005_alter_quiz_is_public'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('session', 'question'), name='unique_session_question'),
        ),
    ]
