# Generated by Django 6.0.1 on 2026-03-10 13:08

import accounts.models
import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'そのユーザー名は既に使用されています。'}, help_text='20文字以内で入力してください。文字、数字、「@.+-_」が使用できます。', max_length=20, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='ユーザー名')),
                ('email', models.EmailField(error_messages={'unique': 'そのメールアドレスは使用できません。'}, help_text='メールアドレスを入力してください。', max_length=254, unique=True, verbose_name='メールアドレス')),
                ('is_staff', models.BooleanField(default=False, help_text='管理者権限を指定します。', verbose_name='管理者権限')),
                ('is_active', models.BooleanField(default=True, help_text='ユーザーがアクティブかどうかを判断します。', verbose_name='アクティブフラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='ユーザー作成日を記録します。', verbose_name='ユーザー作成日')),
                ('is_banned', models.BooleanField(default=False, help_text='BANフラグです。', verbose_name='BANフラグ')),
                ('banned_reason', models.CharField(blank=True, help_text='BAN理由を入力してください。', max_length=300, null=True, verbose_name='BAN理由')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー一覧',
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
