# Generated by Django 6.0.1 on 2026-01-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_remove_question_sort_order_alter_choice_question_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_scorrect',
            new_name='is_correct',
        ),
    ]
