# Generated by Django 6.0.1 on 2026-05-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_course_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
    ]
