# Generated by Django 6.0.1 on 2026-01-24 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_rename_is_scorrect_choice_is_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='discription',
            new_name='description',
        ),
    ]
