# Generated by Django 6.0.1 on 2026-01-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_rename_discription_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
