# Generated by Django 6.0.7 on 2026-07-08 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0005_like_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekLikeRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_likeranking', to='quizzes.course')),
            ],
        ),
    ]
